theme = "ayu_mirage"

[editor]
cursorline = true
lsp.display-inlay-hints = true
lsp.auto-signature-help = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 500

[keys.normal]
"ret" = "goto_word"
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
"R" = ":toggle-option soft-wrap.enable"

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"

[keys.insert]
j = { k = "normal_mode" }
C-c = "signature_help"
