[[language]]
name = "python"
language-servers = ["ruff"]  # , "pyrefly"
auto-format = true

# [language-server.pyrefly]
# command = "pyrefly"
# args = [ "lsp" ]

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "typst"
auto-format = true
formatter.command = "typstyle"

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
